#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Generate a server conf
here=`readlink -f $0`; here=`dirname $here`
root=`readlink -f $1`

host=`cat $root/conf/httpd.conf | grep ServerName | awk '{ print $2 }'`
port=`cat $root/conf/httpd.conf | grep Listen | tail -1 | awk '{ print $2 }'`
ssl=`cat $root/conf/httpd.conf | grep "SSLEngine" | awk '{ print $2 }'`
if [ "$ssl" = "on" ]; then
    protocol="https"

cat >>$root/conf/httpd.conf <<EOF
# Configure SCA SSL support
SCASSLCACertificateFile "$root/conf/ca.crt"
SCASSLCertificateFile "$root/conf/server.crt"
SCASSLCertificateKeyFile "$root/conf/server.key"

EOF

else
    protocol="http"
fi

cat >>$root/conf/httpd.conf <<EOF
# Support for SCA component wiring
LoadModule mod_tuscany_wiring $here/libmod_tuscany_wiring.so
SCAWiringServerName $protocol://$host:$port

EOF
