#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Pass your EC2 public host name
if [ "$1" != "" ]; then
    host=$1
else
    # Default to dummy test domain
    host="sca-store.com"
fi

# Ports 80, 443, 444, 8090, 8453, 8454 need to be open
sudo ../../ubuntu/ip-redirect-all 80 8090
sudo ../../ubuntu/ip-redirect-all 443 8453

../../modules/http/ssl-ca-conf tmp $host
../../modules/http/ssl-cert-conf tmp $host server
../../modules/http/ssl-cert-conf tmp "*.$host" vhost
../../modules/http/httpd-conf tmp $host 8090/80 htdocs
../../modules/http/httpd-event-conf tmp
../../modules/http/vhost-conf tmp domains htdocs
../../modules/http/httpd-ssl-conf tmp 8453/443
../../modules/http/vhost-ssl-conf tmp
../../modules/server/server-conf tmp
../../modules/python/python-conf tmp
cat >>tmp/conf/httpd.conf <<EOF
# Configure SCA Composite for mass dynamic virtual Hosting
SCAVirtualContribution `pwd`/domains/
SCAVirtualComposite store.composite

EOF

../../components/cache/memcached-start
../../modules/http/httpd-start tmp

