#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Generate an Axis2 server conf
here=`readlink -f $0`; here=`dirname $here`
root=`readlink -f $1`
htdocs=`readlink -f $2`
openid_prefix=`cat openid.prefix`

servername=`cat $root/conf/httpd.conf | grep ServerName | tail -1 | awk '{ print $2 }'`
ssl=`cat $root/conf/httpd.conf | grep "SSLEngine" | awk '{ print $2 }'`
if [ "$ssl" = "on" ]; then
    protocol="https"
else
    protocol="http"
fi

# Configure HTTPD mod_auth_openid module
cat >>$root/conf/httpd.conf <<EOF
# Support for OpenID authentication
LoadModule authopenid_module  $openid_prefix/modules/mod_auth_openid.so

<Location /protected>
AuthOpenIDEnabled On
AuthOpenIDCookiePath /
AuthOpenIDLoginPage /protected/login
AuthOpenIDAXAdd EMAIL http://axschema.org/contact/email
AuthOpenIDServerName $servername
</Location>

<Location /components>
AuthOpenIDEnabled On
AuthOpenIDCookiePath /
AuthOpenIDLoginPage /protected/login
AuthOpenIDAXAdd EMAIL http://axschema.org/contact/email
AuthOpenIDServerName $servername
</Location>

<Location /references>
AuthOpenIDEnabled On
AuthOpenIDCookiePath /
AuthOpenIDLoginPage /protected/login
AuthOpenIDAXAdd EMAIL http://axschema.org/contact/email
AuthOpenIDServerName $servername
</Location>

<Location /protected/login>
AuthOpenIDEnabled Off
</Location>

<Location /protected/logout>
AuthOpenIDEnabled Off
</Location>

EOF
