#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Setup
rm -rf tmp
../../components/cache/memcached-start tmp 11212
../../components/cache/memcached-start tmp 11213

../../modules/http/ssl-ca-conf tmp localhost
../../modules/http/ssl-cert-conf tmp localhost
../../modules/http/httpd-conf tmp localhost 8090 htdocs
../../modules/http/httpd-ssl-conf tmp 8453

./openid-conf tmp
./openid-memcached-conf tmp localhost 11212
./openid-memcached-conf tmp localhost 11213
./openid-step2-conf tmp

# For this test to work you need to add your openid user id to the
# password file with a dummy 'password' password, and to the group
# of authorized users
../../modules/http/passwd-auth-conf tmp /openid/jane@example.com password
../../modules/http/group-auth-conf tmp jane@example.com

../../modules/server/server-conf tmp
../../modules/server/scheme-conf tmp
cat >>tmp/conf/httpd.conf <<EOF
SCAContribution `pwd`/
SCAComposite openid.composite
EOF

../../modules/http/httpd-start tmp

