#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Run Python util test cases
here=`readlink -f $0`; here=`dirname $here`
python_prefix=`cat $here/../python/python.prefix`

$python_prefix/bin/python stream-test.py
rc=$?
if [ "$rc" = "0" ]; then
    $python_prefix/bin/python xml-test.py
    rc=$?
fi
if [ "$rc" = "0" ]; then
    $python_prefix/bin/python atom-test.py
    rc=$?
fi
if [ "$rc" = "0" ]; then
    $python_prefix/bin/python rss-test.py
    rc=$?
fi
if [ "$rc" = "0" ]; then
    $python_prefix/bin/python json-test.py
    rc=$?
fi

return $rc
