#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# For this module to work, add the www.example.com domain to your /etc/hosts as follows:
# 127.0.0.1 www.example.com

# Setup
#../../ubuntu/ip-redirect-all 80 8090
#../../ubuntu/ip-redirect-all 443 8453

../../components/cache/memcached-start tmp 11212
../../components/cache/memcached-start tmp 11213

../../modules/http/ssl-ca-conf tmp www.example.com
../../modules/http/ssl-cert-conf tmp www.example.com
../../modules/http/httpd-conf tmp www.example.com 8090 htdocs
../../modules/http/httpd-ssl-conf tmp 8453

./oauth-conf tmp
./oauth-memcached-conf tmp www.example.com 11212
./oauth-memcached-conf tmp www.example.com 11213

# Configure your app keys here
./oauth1-appkey-conf tmp twitter.com app2345 secret7890
./oauth1-appkey-conf tmp linkedin.com app3456 secret4567
./oauth2-appkey-conf tmp facebook.com app1234 secret6789
./oauth2-appkey-conf tmp github.com app5678 secret8901

# For this test to work you need to add your oauth user id to the
# authorized user group
../../modules/http/group-auth-conf tmp jane@example.com

../../modules/server/server-conf tmp
../../modules/server/scheme-conf tmp
cat >>tmp/conf/httpd.conf <<EOF
SCAContribution `pwd`/
SCAComposite oauth.composite
EOF

../../modules/http/httpd-start tmp

