#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# For this module to work, add the www.example.com domain to your /etc/hosts as follows:
# 127.0.0.1 www.example.com

# Test supporting both OpenID and OAuth in the same app
here=`echo "import os; print os.path.realpath('$0')" | python`; here=`dirname $here`

# Setup
rm -rf tmp
../../components/cache/memcached-start tmp 11212
../../components/cache/memcached-start tmp 11213

../../modules/http/ssl-ca-conf tmp www.example.com
../../modules/http/ssl-cert-conf tmp www.example.com
../../modules/http/httpd-conf tmp www.example.com 8090 htdocs
../../modules/http/httpd-ssl-conf tmp 8453

../openid/openid-conf tmp
../openid/openid-step2-conf tmp
../openid/openid-memcached-conf tmp www.example.com 11212
../openid/openid-memcached-conf tmp www.example.com 11213

./oauth12-conf tmp
./oauth-memcached-conf tmp www.example.com 11212
./oauth-memcached-conf tmp www.example.com 11213

# Configure your app keys here
./oauth1-appkey-conf tmp twitter.com app2345 secret7890
./oauth1-appkey-conf tmp linkedin.com app3456 secret4567
./oauth2-appkey-conf tmp facebook.com app1234 secret6789
./oauth2-appkey-conf tmp github.com app5678 secret8901

../../modules/http/open-auth-conf tmp

# For this test to work you need to add your oauth and openid user ids to
# the password file with a dummy 'password' password, and to the group
# of authorized users
../../modules/http/passwd-auth-conf tmp foo foo
../../modules/http/group-auth-conf tmp foo
../../modules/http/passwd-auth-conf tmp /openid/123456 password
../../modules/http/group-auth-conf tmp 123456
../../modules/http/passwd-auth-conf tmp /oauth2/jane@example.com password
../../modules/http/group-auth-conf tmp jane@example.com

../../modules/server/server-conf tmp
../../modules/server/scheme-conf tmp
cat >>tmp/conf/httpd.conf <<EOF
SCAContribution `pwd`/
SCAComposite oauth.composite

Alias /login/index.html $here/htdocs/login/mixed.html

EOF

../../modules/http/httpd-start tmp

