#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Test supporting both OpenID and OAuth in the same app
here=`readlink -f $0`; here=`dirname $here`

# Setup
../../components/cache/memcached-start 11212
../../components/cache/memcached-start 11213

../../modules/http/ssl-ca-conf tmp localhost
../../modules/http/ssl-cert-conf tmp localhost
../../modules/http/httpd-conf tmp localhost 8090 htdocs
../../modules/http/httpd-ssl-conf tmp 8453

./oauth-conf tmp
./oauth-memcached-conf tmp localhost 11212
./oauth-memcached-conf tmp localhost 11213

# Configure your app keys here
./oauth1-appkey-conf tmp twitter.com app2345 secret7890
./oauth1-appkey-conf tmp linkedin.com app3456 secret4567
./oauth2-appkey-conf tmp facebook.com app1234 secret6789
./oauth2-appkey-conf tmp github.com app5678 secret8901

../openid/openid-conf tmp
../openid/openid-step2-conf tmp
../openid/openid-memcached-conf tmp localhost 11212
../openid/openid-memcached-conf tmp localhost 11213

../http/open-auth-conf tmp
../http/passwd-auth-conf tmp foo foo

# For this test to work you need to add your form, oauth and open id ids
# to the authorized user group
../../modules/http/group-auth-conf tmp foo
../../modules/http/group-auth-conf tmp 123456
../../modules/http/group-auth-conf tmp https://www.google.com/accounts/o8/id?id=12345678

../../modules/server/server-conf tmp
../../modules/server/scheme-conf tmp
cat >>tmp/conf/httpd.conf <<EOF
SCAContribution `pwd`/
SCAComposite oauth.composite

Alias /login/index.html $here/htdocs/login/mixed.html

EOF

../../modules/http/httpd-start tmp

