#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

root=$1
port=$2
httpport=$3

# Aggregate database server logs
category=`basename $root`
../../components/log/scribe-tail-start $category "sqldb" $root/logs/postgresql
../../components/log/scribe-tail-start $category $root/logs/error_log
../../components/log/scribe-tail-start $category $root/logs/access_log

# Configure a database backup HTTP server
../../modules/http/httpd-conf $root localhost $httpport $root/htdocs

# Configure a database server
if [ ! -f $root/sqldb/data/postgresql.conf ]; then
    create="true"
else
    create="false"
fi
../../components/sqldb/pgsql-conf $root $port
if [ "$create" = "true" ]; then
    ../../components/sqldb/pgsql-start $root
    ../../components/sqldb/pgsql localhost $port "create table store(key text, value text);" 1>>$root/logs/postgresql 2>&1
    ../../components/sqldb/pgsql-stop $root
fi

