#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Generate SSL certificates
../../modules/http/ssl-ca-conf tmp/ssl sca-store.com
../../modules/http/ssl-cert-conf tmp/ssl sca-store.com server
../../modules/http/ssl-cert-conf tmp/ssl *.sca-store.com vhost
../../modules/http/ssl-cert-conf tmp/ssl sca-store.com proxy
../../modules/http/ssl-cert-conf tmp/ssl sca-store.com tunnel

# Start three memcached servers and a tunnel server
../../components/cache/memcached-start 127.0.0.1:11411
../../components/cache/memcached-start 127.0.0.1:11412
../../components/cache/memcached-start 127.0.0.1:11413
./tunnel-ssl-conf tmp/tunnel1
../../modules/http/httpd-start tmp/tunnel1

# Start three app servers
./server-ssl-conf tmp/server1 8101 8441
../../modules/http/httpd-start tmp/server1

./server-ssl-conf tmp/server2 8102 8442
../../modules/http/httpd-start tmp/server2

./server-ssl-conf tmp/server3 8103 8443
../../modules/http/httpd-start tmp/server3

# Start two proxy balancers
./proxy-ssl-conf tmp/proxy1 8091 8093
../../modules/http/proxy-member-conf tmp/proxy1 localhost 8101
../../modules/http/proxy-ssl-member-conf tmp/proxy1 localhost 8441
../../modules/http/proxy-member-conf tmp/proxy1 localhost 8102
../../modules/http/proxy-ssl-member-conf tmp/proxy1 localhost 8442
../../modules/http/proxy-member-conf tmp/proxy1 localhost 8103
../../modules/http/proxy-ssl-member-conf tmp/proxy1 localhost 8443
../../modules/http/httpd-start tmp/proxy1

./proxy-ssl-conf tmp/proxy2 8092 8094
../../modules/http/proxy-member-conf tmp/proxy2 localhost 8101
../../modules/http/proxy-ssl-member-conf tmp/proxy2 localhost 8441
../../modules/http/proxy-member-conf tmp/proxy2 localhost 8102
../../modules/http/proxy-ssl-member-conf tmp/proxy2 localhost 8442
../../modules/http/proxy-member-conf tmp/proxy2 localhost 8103
../../modules/http/proxy-ssl-member-conf tmp/proxy2 localhost 8443
../../modules/http/httpd-start tmp/proxy2

# Redirect traffic from port 80 to 8091 and use proxy1
#../../ubuntu/ip-redirect-all 80 8091
#../../ubuntu/ip-redirect-all 443 8093

# Redirect traffic from port 80 to 8092 and use proxy2
#../../ubuntu/ip-redirect-all 80 8092
#../../ubuntu/ip-redirect-all 443 8094

