#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

set -x

# Redirect traffic from port 80 to proxy1
sudo ../../ubuntu/ip-redirect-all 80 8090

# Redirect traffic from port 80 to proxy2
#sudo ../../ubuntu/ip-redirect-all 80 8091

# Start scribe logging
rm -rf tmp
../../components/log/scribed-central-conf tmp/monitor
../../components/log/scribed-client-conf tmp/monitor localhost
../../components/log/scribed-central-start tmp/monitor
../../components/log/scribed-client-start tmp/monitor
sleep 1

# Start three memcached servers
../../components/cache/memcached-start tmp 11211
../../components/cache/memcached-start tmp 11212
../../components/cache/memcached-start tmp 11213

# Start a master and two hot standby databases
./sqldb-master-conf tmp/sqldb1 5432 8502
../../components/sqldb/pgsql-start tmp/sqldb1
../../modules/http/httpd-start tmp/sqldb1
sleep 1

./sqldb-standby-conf tmp/sqldb2 5433 8503 localhost 5432 8502
../../components/sqldb/pgsql-start tmp/sqldb2
../../modules/http/httpd-start tmp/sqldb2

./sqldb-standby-conf tmp/sqldb3 5434 8504 localhost 5432 8502
../../components/sqldb/pgsql-start tmp/sqldb3
../../modules/http/httpd-start tmp/sqldb3

# Start three app servers
./server-conf tmp/server1 8101
../../modules/http/httpd-start tmp/server1
sleep 1

./server-conf tmp/server2 8102
../../modules/http/httpd-start tmp/server2
sleep 1

./server-conf tmp/server3 8103
../../modules/http/httpd-start tmp/server3
sleep 1

# Start two proxy balancers
./proxy-conf tmp/proxy1 8090
../../modules/http/proxy-member-conf tmp/proxy1 localhost 8101
../../modules/http/proxy-member-conf tmp/proxy1 localhost 8102
../../modules/http/proxy-member-conf tmp/proxy1 localhost 8103
../../modules/http/httpd-start tmp/proxy1

./proxy-conf tmp/proxy2 8091
../../modules/http/proxy-member-conf tmp/proxy2 localhost 8101
../../modules/http/proxy-member-conf tmp/proxy2 localhost 8102
../../modules/http/proxy-member-conf tmp/proxy2 localhost 8103
../../modules/http/httpd-start tmp/proxy2

