#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Start three memcached servers
../../components/cache/memcached-start 11211
../../components/cache/memcached-start 11212
../../components/cache/memcached-start 11213

# Start three app servers, with a master database and
# two hot standby databases
./server-conf tmp/server1 8101
./sqldb-master-conf tmp/server1 5432
../../components/sqldb/pgsql-start tmp/server1
../../modules/http/httpd-start tmp/server1
sleep 1

./server-conf tmp/server2 8102
./sqldb-standby-conf tmp/server2 localhost 5432 8101 5433
../../components/sqldb/pgsql-start tmp/server2
../../modules/http/httpd-start tmp/server2
sleep 1

./server-conf tmp/server3 8103
./sqldb-standby-conf tmp/server3 localhost 5432 8101 5434
../../components/sqldb/pgsql-start tmp/server3
../../modules/http/httpd-start tmp/server3
sleep 1

# Start two proxy balancers
./proxy-conf tmp/proxy1 8091
../../modules/http/proxy-member-conf tmp/proxy1 localhost 8101
../../modules/http/proxy-member-conf tmp/proxy1 localhost 8102
../../modules/http/proxy-member-conf tmp/proxy1 localhost 8103
../../modules/http/httpd-start tmp/proxy1

./proxy-conf tmp/proxy2 8092
../../modules/http/proxy-member-conf tmp/proxy2 localhost 8101
../../modules/http/proxy-member-conf tmp/proxy2 localhost 8102
../../modules/http/proxy-member-conf tmp/proxy2 localhost 8103
../../modules/http/httpd-start tmp/proxy2

# Redirect traffic from port 80 to 8091 and use proxy1
#../../ubuntu/ip-redirect-all 80 8091

# Redirect traffic from port 80 to 8092 and use proxy2
#../../ubuntu/ip-redirect-all 80 8092

