#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

set -x

../../modules/http/httpd-stop tmp/server1
../../modules/http/httpd-stop tmp/server2
../../modules/http/httpd-stop tmp/server3

../../modules/http/httpd-stop tmp/proxy1
../../modules/http/httpd-stop tmp/proxy2

../../components/cache/memcached-stop 11211
../../components/cache/memcached-stop 11212
../../components/cache/memcached-stop 11213

../../components/sqldb/pgsql-stop tmp/sqldb3
../../modules/http/httpd-stop tmp/sqldb3
../../components/sqldb/pgsql-stop tmp/sqldb2
../../modules/http/httpd-stop tmp/sqldb2
../../components/sqldb/pgsql-stop tmp/sqldb1
../../modules/http/httpd-stop tmp/sqldb1

../../components/log/scribed-client-stop tmp/monitor
../../components/log/scribed-central-stop tmp/monitor
../../components/log/scribe-tail-stop tmp
