#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

root=$1

# Configure SSL tunnels to the memcached servers
../../modules/http/httpd-conf $root localhost 127.0.0.1:11210 htdocs
tar -C tmp/ssl -c `../../modules/http/ssl-cert-find tmp/ssl` | tar -C $root -x
../../modules/http/tunnel-ssl-conf $root 11211 localhost 8441 11411
../../modules/http/tunnel-ssl-conf $root 11212 localhost 8442 11412
../../modules/http/tunnel-ssl-conf $root 11213 localhost 8443 11413

# Configure SSL tunnels to the postgresql servers
../../modules/http/tunnel-ssl-conf $root 5532 localhost 8441 5432
../../modules/http/tunnel-ssl-conf $root 5533 localhost 8441 5433
../../modules/http/tunnel-ssl-conf $root 5534 localhost 8441 5433

