#!/bin/bash

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Open iOS mobile Safari remote inspector
mobsafari=$(ps x | grep "MobileSafari" | grep -v grep | awk '{ print $1 }')
if [ "$mobsafari" == "" ]; then
  echo "Mobile Safari.app not running."
  exit 1
else

    # Enable remote inspector
    cat <<EOF | gdb
attach $mobsafari
p (void *)[WebView _enableRemoteInspector]
detach
EOF

fi

