#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Generate an Axis2 server conf
here=`readlink -f $0`; here=`dirname $here`
root=`readlink -f $1`

# Create an Axis2 home directory
mkdir -p $root/axis2c
ln -f -s $AXIS2C_HOME/lib $root/axis2c/lib
mkdir -p $root/axis2c/logs
mkdir -p $root/axis2c/modules
ln -f -s $AXIS2C_HOME/modules/addressing $root/axis2c/modules/addressing
ln -f -s $AXIS2C_HOME/modules/logging $root/axis2c/modules/logging
mkdir -p $root/axis2c/services

# Install Tuscany Axis2 module and service
mkdir -p $root/axis2c/modules/tuscany
ln -f -s $here/.libs/libaxis2-dispatcher.so $root/axis2c/modules/tuscany/libaxis2-dispatcher.so
ln -f -s $here/module.xml $root/axis2c/modules/tuscany/module.xml
mkdir -p $root/axis2c/services/tuscany
ln -f -s $here/.libs/libaxis2-service.so $root/axis2c/services/tuscany/libaxis2-service.so
ln -f -s $here/services.xml $root/axis2c/services/tuscany/services.xml
cp $here/axis2.xml $root/axis2c/axis2.xml

# Configure HTTPD Axis2 module
cat >>$root/conf/httpd.conf <<EOF
LoadModule axis2_module $root/axis2c/lib/libmod_axis2.so
Axis2RepoPath $root/axis2c
Axis2LogFile $root/axis2c/logs/mod_axis2.log
Axis2LogLevel debug
<Location /axis2>
    SetHandler axis2_module
</Location>
EOF
