#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

echo "Testing..."

# Setup
../../modules/http/httpd-conf tmp 8092 htdocs
cat >>tmp/conf/httpd.conf <<EOF
<Location /Catalog>
SetHandler mod_tuscany
SCAContribution `pwd`/
SCAComponent store
SCAImplementation store.scm
</Location>

<Location /Total>
SetHandler mod_tuscany
SCAContribution `pwd`/
SCAComponent store
SCAImplementation store.scm
</Location>

<Location /ShoppingCart>
SetHandler mod_tuscany
SCAContribution `pwd`/
SCAComponent store
SCAImplementation store.scm
</Location>
EOF
apachectl -k start -d `pwd`/tmp
sleep 1

# Test HTTP GET
curl http://localhost:8092/store.html 2>/dev/null >tmp/store.html
diff tmp/store.html htdocs/store.html
rc=$?

# Cleanup
apachectl -k stop -d `pwd`/tmp
sleep 1
if [ "$rc" = "0" ]; then
    echo "OK"
fi
return $rc
