#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Setup
../../modules/http/httpd-conf tmp localhost 8090 ../../modules/http/htdocs
../../modules/http/httpd-event-conf tmp
../../modules/server/server-conf tmp
../../modules/server/scheme-conf tmp
cat >>tmp/conf/httpd.conf <<EOF
SCAContribution `pwd`/
SCAComposite log.composite
EOF

rm -rf tmp/scribe
./scribed-central-conf tmp
./scribed-client-conf tmp localhost
./scribed-central-start tmp
./scribed-client-start tmp
sleep 1
../../modules/http/httpd-start tmp
sleep 2

# Test
./client-test 2>/dev/null
rc=$?
if [ "$rc" = "0" ]; then
    echo "Testing..."
    sleep 4
    grep "Apple" tmp/scribe/logs/central/default/default_current >/dev/null
    rc=$?
fi
if [ "$rc" = "0" ]; then
    grep "(add 33 22)" tmp/scribe/logs/central/default/default_current >/dev/null
    rc=$?
fi
if [ "$rc" = "0" ]; then
    grep "55" tmp/scribe/logs/central/default/default_current >/dev/null
    rc=$?
fi

# Cleanup
../../modules/http/httpd-stop tmp
sleep 1
./scribed-client-stop tmp
./scribed-central-stop tmp
sleep 1
if [ "$rc" = "0" ]; then
    echo "OK"
fi
exit $rc
