<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:tns="http://www.tuscany.com/tests/duplicate_services.wsdl"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    targetNamespace="http://www.tuscany.com/tests/duplicate_services.wsdl"
    name="duplicate_services">

  <message name="request">
    <part name="zipcode" type="xsd:string"/>
  </message>

  <message name="response">
    <part name="host" type="xsd:string"/>
    <part name="port" type="xsd:string"/>
  </message>

  <portType name="portType">
    <!-- Request/response -->
    <operation name="test">
      <input message="tns:request"/>
      <output message="tns:response"/>
    </operation>
  </portType>

  <binding name="binding" type="tns:portType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="test">
      <soap:operation soapAction="http://www.tuscany.com/test/duplicate_services"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="service">
    <port name="port" binding="tns:binding">
      <soap:address location="http://localhost:8090/tests"/>
      <soap:address location="http://localhost:8090/tests"/>
    </port>
  </service>

</definitions>
