#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Start postgresql
here=`readlink -f $0`; here=`dirname $here`
root=`readlink -f $1`

pgsql_prefix=`cat $here/pgsql.prefix`
mkdir -p $root/sqldb
mkdir -p $root/logs
if [ ! -f $root/sqldb/postgresql.conf ]; then
    $pgsql_prefix/bin/pg_ctl init -D $root/sqldb
    createdb="true"
fi

$pgsql_prefix/bin/pg_ctl start -D $root/sqldb -l $root/logs/postgresql
sleep 1
if [ "$createdb" = "true" ]; then
    $pgsql_prefix/bin/createdb db
fi

