#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Run SQL command
here=`echo "import os; print os.path.realpath('$0')" | python`; here=`dirname $here`
pgsql_prefix=`cat $here/pgsql.prefix`

if [ "$2" = "" ]; then
    host="localhost"
    port="5432"
    cmd="$1"
else
    host="$1"
    port="$2"
    cmd="$3"
fi

if [ "$cmd" = "" ]; then
    $pgsql_prefix/bin/psql -h $host -p $port db
else
    $pgsql_prefix/bin/psql -h $host -p $port -c "$cmd" db
fi

