#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# PostgreSQL archive command
here=`echo "import os; print os.path.realpath('$0')" | python`; here=`dirname $here`
root=`echo "import os; print os.path.realpath('$1')" | python`

host=$2
port=$3
walp=$4
walf=$5

# Copy WAL to archive directory
if [ ! -f $root/sqldb/archive/$walf ]; then
    cp $walp $root/sqldb/archive/$walf
    rc=$?
    if [ "$rc" != "0" ]; then
        exit $rc
    fi
fi

# Trigger a backup if we have 10 WAL files archived since the last backup
lastbak=`ls $root/sqldb/archive | sort -r | grep "\.backup$" | head -1`
if [ "$lastbak" = "" ]; then
    exit 0
fi
wals=`ls $root/sqldb/archive | sort -r | grep -v "\.backup\.tar\.gz$"`

w=0
for f in $wals; do
    if [ "$f" = "$lastbak" ]; then
        break
    fi
    w=$((w+1))

    if [ "$w" = "10" ]; then
        nohup /bin/sh -c "$here/pgsql-backup $root $host $port" 1>/dev/null 2>/dev/null &
        break
    fi
done

exit 0

