#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Setup
../../modules/http/httpd-conf tmp/master localhost 8090 tmp/master/htdocs
./pgsql-conf tmp/master 5432
./pgsql-start tmp/master
./pgsql localhost 5432 "drop table test;" 1>/dev/null 2>&1
./pgsql localhost 5432 "create table test(key text, value text);" 1>/dev/null 2>&1
../../modules/http/httpd-start tmp/master
sleep 2
./pgsql-standby-conf tmp/standby 5433 localhost 5432 8090
./pgsql-start tmp/standby

# Test
./pgsql-standby-test 2>/dev/null
rc=$?

# Cleanup
../../modules/http/httpd-stop tmp/master
./pgsql-stop tmp/standby
./pgsql-stop tmp/master
exit $rc
