#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Create app links and sub-directories if needed
for n in `ls apps | awk '{ printf "apps/%s/nuvem\n", $1 }'`; do
    if [ ! -e "$n" ]; then
        ln -s ../../../../../nuvem/nuvem-parallel/nuvem "$n"
    fi
done

for n in `ls apps | awk '{ printf "apps/%s/lib\n", $1 }'`; do
    if [ ! -e "$n" ]; then
        ln -s ../../../../components "$n"
    fi
done

for n in `ls apps | awk '{ printf "apps/%s/htdocs\n", $1 }'`; do
    if [ ! -e "$n" ]; then
        mkdir "$n"
        ln -s ../../../htdocs/cache-manifest.cmf "$n/cache-manifest.cmf"
        ln -s ../../../htdocs/login "$n/login"
        ln -s ../../../htdocs/logout "$n/logout"
        ln -s ../../../htdocs/public "$n/public"
        ln -s ../../../htdocs/data "$n/data"
        ln -s ../../../htdocs/app/index.html "$n/index.html"
        ln -s ../../../htdocs/robots.txt "$n/robots.txt"
        ln -s ../../../htdocs/favicon.ico "$n/favicon.ico"
        ln -s ../app.html "$n/app.html"
    fi
done

