#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# For this module to work, add the sca-store.com domain to your /etc/hosts as follows:
# 127.0.0.1 sca-store.com

here=`echo "import os; print os.path.realpath('$0')" | python`; here=`dirname $here`
jsprefix=`echo "import os; print os.path.realpath('$here/../js')" | python`

# Configure server
../../modules/http/httpd-conf tmp sca-store.com 8090 htdocs
../../modules/http/httpd-event-conf tmp

# Configure Python component support
../server/server-conf tmp
../python/python-conf tmp

# Configure error pages
cat >>tmp/conf/svhost.conf <<EOF
# Error pages
ErrorDocument 404 /notfound/
ErrorDocument 401 /notauth/
ErrorDocument 500 /oops/

# Redirect www to main home page
RewriteEngine on
RewriteCond %{HTTP_HOST} ^www\.sca-store\.com [NC]
RewriteCond %{SERVER_PORT} !^80$
RewriteRule .* http://sca-store.com:%{SERVER_PORT}%{REQUEST_URI} [L,R]
RewriteCond %{HTTP_HOST} ^www\.sca-store\.com [NC]
RewriteRule .* http://sca-store.com%{REQUEST_URI} [L,R]

EOF

# Configure SCA contributions
cat >>tmp/conf/httpd.conf <<EOF
# Configure SCA Composite
SCAContribution `pwd`/
SCAComposite edit.composite

# Configure SCA Composite for mass dynamic virtual Hosting
SCAVirtualContribution `pwd`/apps/
SCAVirtualComposite app.composite

EOF

# Configure resource aliases
cat >>tmp/conf/httpd.conf <<EOF

Alias /home/home.png $here/htdocs/home/home.png
Alias /home/home.b64 $here/htdocs/home/home.b64

EOF

# Create app links and sub-directories if needed
./mkapplinks

# Configure app resource aliases
cat >>tmp/conf/svhost.conf <<EOF

<Location /v>
RewriteEngine on

# Map /v/<app-name>/<path> to htdocs/app/<path>
RewriteCond %{REQUEST_URI} ^/v/.+/.*$
RewriteRule /v/(.+)/(.*)$ $here/htdocs/app/\$2 [L]

# Redirect /v/<app-name> to /<app-name>/
RewriteCond %{REQUEST_URI} ^/v/[^/]+$
RewriteRule /v/([^/]+)$ /\$1/ [L,R]

</Location>

EOF

# Create application database directories
mkdir -p tmp/appdata/filedb

# Start memcached
../../components/cache/memcached-start 11211

# Start server
../http/httpd-start tmp

