#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

here=`readlink -f $0`; here=`dirname $here`
jsprefix=`readlink -f $here/../js`

../http/httpd-conf tmp localhost 8090 htdocs
cat >>tmp/conf/httpd.conf <<EOF
# Override CSS
Alias /ui.css $jsprefix/htdocs/uiblue.css

EOF
../server/server-conf tmp
../python/python-conf tmp
cat >>tmp/conf/httpd.conf <<EOF
# Configure SCA Composite
SCAContribution `pwd`/
SCAComposite edit.composite

EOF

../../components/cache/memcached-start 11211
../http/httpd-start tmp

