<?xml version="1.0" encoding="ASCII"?>
<module xmlns="http://www.osoa.org/xmlns/sca/0.9" 
	xmlns:v="http://www.osoa.org/xmlns/sca/values/0.9" 
	name="WSEntryPointTestRPCModule">

	<!-- Expose as a web service -->
	<entryPoint name="WSEntryPointTestRPCEntrypoint" multiplicity="1..1">
		<interface.wsdl interface="WSEntryPointTestRPC.wsdl" callbackInterface=""></interface.wsdl>
		<binding.ws port="http://www.WSEntryPointTest.org/WSEntryPointTestRPC/#wsdl.endpoint(WSEntryPointTestRPC/WSEntryPointTestRPCSOAP)"></binding.ws>
		<reference>WSEntryPointTestRPCServiceComponent</reference>
	</entryPoint>


	<component name="WSEntryPointTestRPCServiceComponent">
		<implementation.cpp dll="WSEntryPointTestRPCModule.dll" header="WSEntryPointTestRPCImpl.h"></implementation.cpp>
                <properties> </properties>
		<references> </references>
	</component>
</module>
