#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

echo "Testing..."
mkdir -p tmp
mkdir -p tmp/conf
cp test-conf/* tmp/conf
cat >tmp/conf/httpd.conf <<EOF
ServerName 127.0.0.1
Listen 9090
DocumentRoot `pwd`/test-htdocs
EOF
mkdir -p tmp/logs
apachectl -k start -d `pwd`/tmp
sleep 1
curl http://localhost:9090/index.html 2>&1 | grep "It works" >/dev/null
rc=$?
apachectl -k stop -d `pwd`/tmp
if [ "$rc" = "0" ]; then
    echo "OK"
fi
return $rc
