#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Parse a string in the form ip-addr:local-port/public-port
addr=`echo $2 | awk -F "/" '{ print $1 }'`
ip=`echo $addr | awk -F ":" '{ print $1 }'`
port=`echo $addr | awk -F ":" '{ print $2 }'`
if [ "$port" = "" ]; then
    port=$ip
    ip=""
    listen=$port
    vhost="*:$port"
else
    listen="$ip:$port"
    vhost="$ip:$port"
fi
pport=`echo $2 | awk -F "/" '{ print $2 }'`
if [ "$pport" = "" ]; then
    pport=$port
fi

# Return the requested part
if [ "$1" = "ip" ]; then
    echo $ip
fi
if [ "$1" = "port" ]; then
    echo $port
fi
if [ "$1" = "pport" ]; then
    echo $pport
fi
if [ "$1" = "listen" ]; then
    echo $listen
fi
if [ "$1" = "vhost" ]; then
    echo $vhost
fi
