#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Setup
./httpd-conf tmp localhost 8091/8090 htdocs
./httpd-event-conf tmp
./httpd-start tmp
./httpd-conf tmp/proxy localhost 8090 tmp/proxy/htdocs
./httpd-event-conf tmp/proxy
./proxy-conf tmp/proxy
./proxy-member-conf tmp/proxy localhost 8091
./httpd-start tmp/proxy
sleep 2

# Test
./curl-test 2>/dev/null
rc=$?

# Cleanup
./httpd-stop tmp/proxy
./httpd-stop tmp
sleep 2
exit $rc
