<?xml version="1.0" encoding="UTF-8"?>
<!--
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at
   
     http://www.apache.org/licenses/LICENSE-2.0
     
   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.
-->

<definitions
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:tns="http://www.tuscany.com/tests/simple.wsdl"
  targetNamespace="http://www.tuscany.com/tests/simple.wsdl"
  name="simple">

  <message name="request">
    <part name="zipcode" type="xsd:string"/>
  </message>

  <message name="response">
    <part name="host" type="xsd:string"/>
    <part name="port" type="xsd:string"/>
  </message>

  <portType name="simplePortType">
    <operation name="simpleOperation">
      <input message="tns:request"/>
      <output message="tns:response"/>
    </operation>
  </portType>

  <binding name="simpleBinding" type="tns:simplePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <!--soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/-->
    <operation name="simpleOperation">
      <soap:operation soapAction="http://www.tuscany.com/test/simpleOperation"/>

      <input>
        <soap:body use="literal"/>
        <!-- this is a bug in SDO or the wsdl schemas: it parses incorrectly
        <soap:body use="encoded"
           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
           namespace="http://www.tuscany.com/tests"/>
        -->
      </input>

      <output>
        <soap:body use="literal"/>
      </output>

    </operation>
  </binding>

  <service name="simpleService">
    <port name="simplePort" binding="tns:simpleBinding">
      <soap:address location="http://localhost/sca/tests"/>
    </port>
  </service>

</definitions>
