#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

here=`echo "import os; print os.path.realpath('$0')" | python`; here=`dirname $here`
cd $here
httpd_prefix=`cat $here/../../modules/http/httpd.prefix`

email=$1
user=$2
pass=$3

tmp=$4
if [ "$tmp" = "" ]; then
    tmp="$here/tmp"
fi
mkdir -p $tmp/sqldb

host=$5
if [ "$host" = "" ]; then
    host="localhost"
fi

# Get password hash
rm -f $tmp/sqldb/load-authn.passwd
touch $tmp/sqldb/load-authn.passwd
$httpd_prefix/bin/htpasswd -b $tmp/sqldb/load-authn.passwd "$email" "$pass" 2>/dev/null
hash=`cat $tmp/sqldb/load-authn.passwd | awk -F ":" '{ print $2 }'`
rm -f $tmp/sqldb/load-authn.passwd

# Compute user id
id="\"$email\""

# Load into database
cat >$tmp/sqldb/load-authn.sql <<EOF
insert into data values('("authn" $id "user.authn")', '((entry (title "$email") (id "$email") (content (user "$user") (hash "$hash"))))');
EOF

$here/../../components/sqldb/pgsql <$tmp/sqldb/load-authn.sql

