#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Stop memcached
here=`echo "import os; print os.path.realpath('$0')" | python`; here=`dirname $here`
root=`echo "import os; print os.path.realpath('$1')" | python`

addr=$2
if [ "$addr" = "" ]; then
    ip=""
    port="11211"
else
    ip=`$here/../../modules/http/httpd-addr ip $addr`
    port=`$here/../../modules/http/httpd-addr port $addr`
fi

memcached_prefix=`cat $here/memcached.prefix`
if [ "$ip" = "" ]; then
    mc="$memcached_prefix/bin/memcached -d -m 4 -p $port"
else
    mc="$memcached_prefix/bin/memcached -d -l $ip -m 4 -p $port"
fi

k=`ps -ef | grep -v grep | grep "${mc}" | awk '{ print $2 }'`
if [ "$k" != "" ]; then
    kill $k
fi

