#!/bin/sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#    
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# Setup
../../modules/http/httpd-conf tmp localhost 8090 ../../modules/http/htdocs
../../modules/server/server-conf tmp
../../modules/server/scheme-conf tmp
cat >>tmp/conf/httpd.conf <<EOF
SCAContribution `pwd`/
SCAComposite memcache.composite
EOF

./memcached-start 11211
./memcached-start 11212
./memcached-start 11213
./memcached-start 11411
./memcached-start 11412
./memcached-start 11413
../../modules/http/httpd-start tmp
sleep 2

# Test
./client-test 2>/dev/null
rc=$?

# Cleanup
../../modules/http/httpd-stop tmp
./memcached-stop 11211
./memcached-stop 11212
./memcached-stop 11213
./memcached-stop 11411
./memcached-stop 11412
./memcached-stop 11413
sleep 2
return $rc
